import type { Metadata } from 'next'
import Image from "next/image";
import Link from "next/link";
import Block from "@/components/Block"
import PageHeader from "@/components/PageHeader";

export const metadata: Metadata = {
  title: 'Lunar Landon',
  description: 'The Lunar Landing puzzle game remade on the Sutherlandon App',
}

export default function Page() {
  return (
    <div>
      <PageHeader
        title='Lunar Landon'
        launchHref='https://lunar-landon.sutherlandon.com'
      />
      <Block className='mb-8'>
        <Image
          src='/img/showcase/lunar-landon.png'
          width='643'
          height='340'
          alt='Lunar Landon Showcase'
          className='max-w-full'
          fetchPriority='high'
        />
      </Block>
      <Block>
        Lunar Landing was is hand held puzzle game that I played on road trips when I was a kid. The goal is to
        The red space shuttle to the airlock in the middle of the board.  There are helper bots that keep the shuttle
        from sailing out to space.  The original game came with 40 puzzles.
      </Block>
      <Block>
        This was my first experiment writing code entirely with AI.  All the code in this project was generated by
        Grok 3.0.  It handled the interface components extremly well, doing exactly what I wanted with one or
        two iterations.  The game logic was much more difficult and I still haven&apos;t gotten it to fully understand 
        to the point it can generate more puzzles.
      </Block>
      <Block>
        App: <Link href='https://lunar-landon.sutherlandon.com' className='underline text-blue-500'>lunar-landon.sutherlandon.com</Link><br />
        Source: <Link href='https://github.com/sutherlandon/lunar-landing' className='underline text-blue-500'>Lunar Landon on Github</Link>
      </Block>
    </div>
  );
}